(function(){"use strict";const CTK=window.CTK=window.CTK||{},D=CTK.Data;
const has=(r,id)=>r.enemy.mutations.includes(id), st=(r,id)=>r.player.upgrades[id]||0;
CTK.Effects={has,st,
 enemyArmor(r,ignore){return ignore?0:Math.max(0,(has(r,"armor_plates")?1:0)+r.combat.temporaryEnemyArmor-(st(r,"armor_breaker")?2:0));},
 attackBonus(r){let n=st(r,"honed_edge")+st(r,"master_edge")*3;if(st(r,"first_blood")&&!r.combat.firstStrikeUsed)n+=6;if(st(r,"heavy_rhythm")&&(r.combat.strikesThisTurn+1)%3===0)n+=8;if(st(r,"executioner")&&r.enemy.hp<=r.enemy.maxHp*.3)n+=4;if(r.combat.bloodRushReady)n+=5;return n;},
 chargeBonus(r,stacks){const c=stacks === undefined ? r.player.chargeStacks : stacks;return c?(c*(r.player.chargeBase+st(r,"focused_charge"))+(st(r,"overpower")?5:0)):0;},
 guard(r){return Math.max(3,r.player.guardBase+st(r,"reinforced_guard")+st(r,"iron_wall")*4-r.combat.corrosionStacks);},
 onEnemyDamage(r){const c=r.combat;if(has(r,"enrage")&&!c.enraged&&r.enemy.hp<=r.enemy.maxHp*.4){c.enraged=true;CTK.State.log(r,"광폭화 발동 → 적 공격력 +4");}if(has(r,"berserker")){[.75,.5,.25].forEach((x,i)=>{if(r.enemy.hp<=r.enemy.maxHp*x&&!c.berserkerThresholdsTriggered.includes(i)){c.berserkerThresholdsTriggered.push(i);CTK.State.log(r,"진정한 광전사 → 공격력 +2");}});}},
 enemyAttack(r,enemyTurnsCompleted){const turns=enemyTurnsCompleted === undefined ? r.combat.enemyTurnsCompleted : enemyTurnsCompleted;let n=r.enemy.baseAttack+(has(r,"sharp_claws")?1:0)+(r.combat.enraged?4:0)+r.combat.berserkerThresholdsTriggered.length*2+r.enemy.roarBonus;if(has(r,"doom_clock")){if(turns+1>=7)n+=5;if(turns+1>=9)n+=5;}if(!r.combat.firstEnemyAttackDone&&has(r,"ambush"))n+=4;if(r.combat.frenzyReady)n+=4;if(r.combat.punisherReady)n+=6;return n;},
 startTurn(r){const c=r.combat;c.turn++;if(c.turn>1)r.player.block=0;c.temporaryEnemyArmor=0;c.playerActionsThisTurn=0;c.strikesThisTurn=0;c.guardsThisTurn=0;c.damageToEnemyThisTurn=0;c.counterlashUsed=false;c.reversalUsed=false;c.ap=r.player.maxAp-(has(r,"fatigue_aura")&&c.turn%4===0?1:0)+(st(r,"adrenaline")&&c.turn===1?1:0)+(st(r,"last_stand")&&r.player.hp<=r.player.maxHp*.3?1:0);if(has(r,"barricade")&&c.turn%3===0){r.enemy.block+=8;CTK.State.log(r,"주기적 방벽 → 적 Block +8");}if(c.shieldEnginePending){r.enemy.block+=10;c.shieldEnginePending=false;CTK.State.log(r,"보호막 엔진 → 적 Block +10");}c.mistConcealed=has(r,"mist")&&c.turn%4===0;if(c.mistConcealed)CTK.State.log(r,"안개 → Intent 은닉");if(has(r,"fatigue_aura")&&c.turn%4===0)CTK.State.log(r,"피로 오라 → AP -1");},
 endPlayerTurn(r){if(has(r,"bleeding_aura")&&r.combat.turn<=4)CTK.Combat.applyPlayerDamage(r,2,"출혈 오라");if(!CTK.Combat.terminal(r)&&has(r,"punisher")&&r.player.block===0){r.combat.punisherReady=true;CTK.State.log(r,"응징자 → 다음 공격 +6");}r.enemy.block=0;},
};}());
