(function(){"use strict";const CTK=window.CTK=window.CTK||{},C=CTK.Constants,D=CTK.Data;
function mutations(r){let used=[];for(const t of C.MUTATION_TIERS[r.round]){let p=D.mutations.filter(x=>x.tier===t&&!r.enemy.mutations.includes(x.id)&&!used.includes(x.id)&&!x.incompatibleWith.some(v=>r.enemy.mutations.includes(v)));let x=CTK.RNG.pick(r,p);if(x)used.push(x.id);}r.pendingMutationChoices=used;}
function rewards(r){let used=[];for(const rarity of C.REWARD_RARITIES[r.selectedRisk]){let p=D.upgrades.filter(x=>x.rarity===rarity&&!used.includes(x.id)&&(r.player.upgrades[x.id]||0)<x.maxStacks);let x=CTK.RNG.pick(r,p);if(x)used.push(x.id);}r.pendingRewardChoices=used;}
function save(){CTK.Storage.saveRun(CTK.app.run);CTK.UI.render();}function finalize(){let r=CTK.app.run;if(!r.finalScoreApplied){r.score+=r.player.hp*10;r.finalScoreApplied=true;let m=CTK.app.meta;m.highScore=Math.max(m.highScore,r.score);m.highestRound=Math.max(m.highestRound,r.round);if(r.phase==="VICTORY")m.totalClears++;CTK.Storage.saveMeta(m);}save();}
function act(t){let r=CTK.app.run;if(!r||r.phase!=="PLAYER_TURN")return;let wasCharged=t==="strike"&&r.player.chargeStacks>0;if(!r.combat.firstAction)r.combat.firstAction=t;if(CTK.Combat.playerAction(r,t)){CTK.Audio.play(t==="strike"?(wasCharged?"heavy":"attack"):t==="guard"?"guard":"select");if(CTK.Combat.terminal(r))finalize();else save();}}
function end(){let r=CTK.app.run;if(!r||r.phase!=="PLAYER_TURN")return;CTK.Effects.endPlayerTurn(r);if(CTK.Combat.terminal(r))return finalize();r.phase="ENEMY_RESOLVE";CTK.Enemy.resolve(r);if(CTK.Combat.terminal(r))finalize();else save();}
function select(id){let r=CTK.app.run;if(r.phase==="MUTATION_SELECT"&&r.pendingMutationChoices.includes(id)){r.enemy.mutations.push(id);r.selectedRisk=D.mutationById[id].tier;rewards(r);r.phase="REWARD_SELECT";CTK.Audio.play("select");save();}else if(r.phase==="REWARD_SELECT"&&r.pendingRewardChoices.includes(id)){CTK.State.addUpgrade(r,id);CTK.State.resetCombat(r);CTK.Enemy.start(r);CTK.Audio.play("select");save();}}
function start(){let r=CTK.State.create(CTK.RNG.newSeed());CTK.app.run=r;CTK.app.meta.totalRuns++;mutations(r);save();}function next(){let r=CTK.app.run;r.round++;r.phase="MUTATION_SELECT";mutations(r);save();}
CTK.app={run:null,meta:null,settings:null};document.addEventListener("DOMContentLoaded",()=>{CTK.app.meta=CTK.Storage.meta();CTK.app.settings=CTK.Storage.settings();CTK.app.run=CTK.Storage.loadRun();CTK.UI.render();document.body.addEventListener("click",e=>{let b=e.target.closest("[data-new],[data-action],[data-select],[data-setting]");if(!b)return;if(b.dataset.new!==undefined)start();else if(b.dataset.action==="end")end();else if(b.dataset.action==="next")next();else if(b.dataset.action)act(b.dataset.action);else if(b.dataset.select)select(b.dataset.select);else {CTK.app.settings[b.dataset.setting]=!CTK.app.settings[b.dataset.setting];CTK.Storage.saveSettings(CTK.app.settings);CTK.UI.render();}});document.addEventListener("keydown",e=>{let map={"1":"strike","2":"guard","3":"charge"};if(map[e.key]){e.preventDefault();act(map[e.key]);}if(e.code==="Space"){e.preventDefault();end();}});});}());
